# Less frequently used parameters shared by all models
img_dims: ${data.img_dims}  # Image dimensions
max_channels: 512  # Maximum number of channels
num_examples: 16  # Number of examples to generate
