name: generative
channels:
  - conda-forge
dependencies:
  - python=3.11.8
  - pip=24.0
  - mypy=1.9.0
  - pre-commit=3.7.0
  - pytest=8.1.1
  - tox=4.14.2
  - pip:
    - tensorflow[and-cuda]==2.16.1
