defaults:
  - data: celeba_hq_256  # Training dataset
  - model: gans/dcgan  # Model to be trained
  - _self_

run_folder: ???  # Experiment folder
run_name: ???  # Experiment name

batch_size: 128  # Batch size for training
epochs: 100  # Number of epochs
save_freq: 10  # Save every N epochs

data:
  img_dims: null  # Image dimensions
