defaults:
  - data: mnist  # Training dataset
  - model: gans/dcgan  # Model to be trained
  - _self_

run_folder: /home/m.pinnock/programming/generative-models/runs
run_name: dcgan_cifar10

batch_size: 128  # Batch size for training
epochs: 100  # Number of epochs
save_freq: 10  # Save every N epochs

data:
  img_dims: null  # Image dimensions

model:
  latent_dim: 100  # Latent dimension
