defaults:
  - data: mnist  # Training dataset
  - model: gans/dcgan  # Model to be trained
  - _self_

batch_size: 128  # Batch size for training
epochs: 100  # Number of epochs

data:
  img_dims: null  # Image dimensions

model:
  latent_dim: 100  # Latent dimension
