defaults:
  - data: mnist  # Training dataset
  - model: gans/dcgan  # Model to be trained
  - _self_

model:
  batch_size: 32  # Batch size for training
  img_dims: null  # Image dimensions

  discriminator_channels: 8  # Number of channels in the discriminator first layer
  generator_channels: 8  # Number of channels in the generator first layer
  latent_dim: 128  # Latent dimension
